version: '2'
services:
    bibelbibliothek-app:
        image: bibelbibliothek
        external_links:
            - bibelbibliothek-mysql:mysql
            - bibelbibliothek-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bibelbibliothek?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    bibelbibliothek-mysql:
        extends:
            file: mysql.yml
            service: bibelbibliothek-mysql
    bibelbibliothek-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bibelbibliothek-elasticsearch
